config/routes.rb
Invoicebear::Application.routes.draw do
  get "dashboard/show"

  resources :payment_notifications

  get "public_pages/index"

  resources :users
  resource :session, :controller => 'user_sessions'

  resources :items

  resources :contacts

  resources :invoices

     match 'features' => 'public_pages#features', :as => :features
     match 'pricing' => 'public_pages#pricing', :as => :pricing
     match 'about' => 'public_pages#about', :as => :about
     match 'contact-us' => 'public_pages#contact', :as => :contact_us
     
     match 'login' => 'user_sessions#new', :as => :login
     match 'logout' => 'user_sessions#destroy', :as => :logout
     match 'signup' => 'users#new', :as => :sign_up
     
     match 'dashboard' => 'invoices#dashboard', :as => :dashboard
     
     match 'inv/:invoice_id' => 'invoices#client_show', :as => :client_show
     
     match 'invoices/send_invoice_notification/:invoice_id' => 'invoices#send_invoice_notification'

   root :to => 'public_pages#index'

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	
	has_many :items, :dependent => :destroy
	belongs_to :contact
	belongs_to :user
	accepts_nested_attributes_for :items, :allow_destroy => true
	
	validates :title, :number, :presence => true
	


  def total
    @total = 0
    self.items.each do |item|
     @total += item.total_price
    end

    @total
  end
  
  def paypal_url(return_url, notify_url)
    values = {
      :business => 'kevin_1334464039_biz@kevincollignon.com',
      :cmd => '_cart',
      :upload => 1,
      :return => return_url,
      :invoice => id,
      :notify_url => notify_url
    }
    items.each_with_index do |item, index|
      values.merge!({
        "amount_#{index+1}" => item.unit_cost,
        "item_name_#{index+1}" => item.description,
        "item_number_#{index+1}" => item.id,
        "quantity_#{index+1}" => item.quantity
      })
    end
    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end
  
  scope :outstanding, lambda { where(['status != ?', "paid"]) }
  
  def total_owed
    @invoices.sum(:total)
  end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  before_filter :require_user, :except => [:client_show]
 

  # GET /invoices
  # GET /invoices.json

  
  def index
    @invoices = Invoice.where(:user_id => current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invoices }
    end
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @invoice = Invoice.find(params[:id])
    
    if @invoice.user_id != current_user.id
		flash[:error] = "you do not have access here"
		redirect_to(:action => 'index') and return
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invoice }
      format.pdf { render :layout => false }
    end
  end
  
  def client_show
    @invoice = Invoice.find(params[:invoice_id])
    
    respond_to do |format|
      format.html { render :layout => false }#client_show.html.erb
      format.pdf { render :layout => false }
    end
  end

  # GET /invoices/new
  # GET /invoices/new.json
  def new
    @invoice = Invoice.new

    1.times do
      item = @invoice.items.build
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invoice }
    end
  end

  # GET /invoices/1/edit
  def edit
    @invoice = Invoice.find(params[:id])
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(params[:invoice])

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render json: @invoice, status: :created, location: @invoice }
      else
        format.html { render action: "new" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def send_invoice_notification
    
    @i = Invoice.find(params[:invoice_id])
    

    # Tell the InvoiceMailer to send a notification email
      InvoiceMailer.invoice_notification(@i).deliver
      
    invoice = @i
    invoice.update_attributes(:status => "sent")
    invoice.save!
    
    
    respond_to do |format|
        format.html { redirect_to "/invoices", notice: "Invoice notification was successfully sent to your contact!" }
        format.json
    end
  end

  # PUT /invoices/1
  # PUT /invoices/1.json
  def update
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      if @invoice.update_attributes(params[:invoice])
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def dashboard
    @invoices = Invoice.where(:user_id => current_user.id)
    @owed = @invoices.outstanding.each.sum {|i| i.total }
    @billed = @invoices.each.sum {|i| i.total }
    @received = @billed - @owed
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url }
      format.json { head :ok }
    end
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice, :html => {:class => ""} ) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="control-group">
    <%= f.label :number %>
    <%= f.number_field :number %>
  </div>
  <div class="control-group">
    <%= f.label :status %>
    <%= f.select :status, ['draft', 'sent', 'paid'].collect { |s| [t('.'+s), s] } %>
  </div>
  <div class="control-group">
	<%= f.label :client_id %><br />
	<%= select_tag "invoice[contact_id]", options_from_collection_for_select(Contact.where(:user_id => current_user.id),"id","bname") %>
	<%= f.hidden_field :user_id, :value => current_user.id %>
  </div>

<div>
<!-- Survey Items display -->
<%= f.fields_for :items do |builder| %>
  <%= render "item_fields", :f => builder %>
<% end %>
<p align="right"><%= link_to_add_fields " + Add New Item", f, :items %></p>
</div>

  <div class="actions">
    <%= f.submit :class => "btn btn-success" %>
  </div>
<% end %>

app/views/invoices/_item_fields.html.erb
<div class="row">
<div class="fields span12" class="invoice_items_list">
<table class="table table-striped table-condensed">
<thead>
<tr class="header">
<td>Description</td>
<td>Unit Cost</td>
<td>Quantity</td>
<td>Discount</td>
<td>Total</td>
<td></td>
</tr>
</thead>

<tr>
<td class="invoice_description"><%= f.text_area :description, :class => "span4" %></td>
<td class="invoice_unit_cost"><%= f.text_field :unit_cost, :class => "span2" %></td>
<td class="invoice_quantity"><%= f.number_field :quantity, :class => "span2" %></td>
<td class="invoice_discount"><%= f.text_field :discount, :class => "span2" %></td>
<td class="invoice_item_total">$0.00</td>
<td><%= link_to_remove_fields "remove", f %></td>
</tr>
</table>
</div>
</div>

app/views/invoices/client_show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InvoiceBear</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <link href='http://fonts.googleapis.com/css?family=Maven+Pro' rel='stylesheet' type='text/css'>
  <style>
body {margin:0;padding:0;background:#5FBDCE;font-family:Verdana,Arial,Times;margin-top:60px;font-size:12px;}

#container {width:850px;margin:0 auto;}

#main-content {background:white;float:left;width:670px;padding:10px 5px 10px 5px;-moz-box-shadow: 0px 0px 5px #888;
-webkit-box-shadow: 0px 0px 5px #888;
box-shadow: 0px 0px 5px #888;}
#sidebar {background:#006363;float:left;width:170px;background:white;margin-top:20px;-webkit-border-top-left-radius: 5px;
-webkit-border-bottom-left-radius: 5px;
-moz-border-radius-topleft: 5px;
-moz-border-radius-bottomleft: 5px;
border-top-left-radius: 5px;
border-bottom-left-radius: 5px;}
.footer {text-align:center;padding:10px 0px;color:white;width:750px;margin:0 auto;padding-top:10px;}

span.clear-fix {clear:both;padding:0;margin:0;}

.invoice_details table {width:100%;margin-top:15px;font-size:11px;}
.invoice_details table tr.header, .invoice_details table tr.header td {background:#E6E6E6;border-bottom:1px solid #A1A1A1;padding:5px 2px 5px 2px;font-weight:bold;}
.invoice_details table td {padding:10px 0px 10px 0px;border-bottom:1px solid #f5f5f5;}

.invoice_qty, .invoice_discount, .invoice_item_total, .invoice_unit_cost {text-align:center;}

div.totals {font-size:12px;padding:10px;font-weight:bold;}

#invoice_info td {padding:5px 2px 10px 5px;}
</style>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div id="container">
	<% if @invoice.status == "paid" %>
	<div style="width:700px;margin:0 auto;background:white;padding:15px;">
	<h2 style="color:green;">This Invoice for the amount of <%= number_to_currency(@invoice.total) %> has been paid. Thank you!</h2>
	</div>
	<% else %>
	<div id="sidebar">
		<p><%= link_to image_tag("paypal_pay_now.gif", :border => 0), @invoice.paypal_url(invoices_url,payment_notifications_url), :class => 'dock-item' %></p>
	</div>
	
	<div id="main-content">
		<div class="invoice_content">
		<h2>Invoice (<%= number_to_currency(@invoice.total) %>)</h2>
		<table border="0" bordercolor="#FFCC00" style="background-color:#FFF" width="100%" cellpadding="0" cellspacing="0" id="invoice_info">
			<tr>
				<td><b>Invoice Summary</b></td>
				<td><%= @invoice.title %></td>
			</tr>
			<tr>
				<td><b>Date</b></td>
				<td><%= @invoice.created_at.to_s(:simple) %></td>
			</tr>
			<tr>
				<td><b>Invoice Number</b></td>
				<td><%= @invoice.number %></td>
			</tr>
			<tr>
				<td><b>Client Details</b></td>
				<td><%= @invoice.contact.bname %><br /> <%= @invoice.contact.address %> <%= @invoice.contact.city %>, <%= @invoice.contact.state %>, <%= @invoice.contact.zip %></td>
			</tr>
		</table>
		</div>
		
		<div class="invoice_details">
			<table cellpadding="0" cellspacing="0">
			<tr class="header">
			<td width="300">Description</td>
			<td width="100" class="invoice_unit_cost">Unit Cost</td>
			<td width="70" class="invoice_qty">Quantity</td>
			<td width="100"class="invoice_discount">Discount</td>
			<td width="100" class="invoice_item_total">Total</td>
			</tr>

			<% @invoice.items.each do |item| %>
			<tr class="items">
			<td class="invoice_description"><%= item.description %></td>
			<td class="invoice_unit_cost"><%= number_to_currency(item.unit_cost) %></td>
			<td class="invoice_qty"><%= item.quantity %></td>
			<td class="invoice_discount"><%= number_to_percentage(item.discount) %></td>
			<td class="invoice_item_total"><%= number_to_currency(item.total_price) %></td>
			</tr>
			<% end %>
			</table>
			<div class="totals" align="right"><b>Total Due:</b> <%= number_to_currency(@invoice.total) %></div>
		</div>
	</div>
 	<span class="clear-fix">&nbsp;</span>
</div><!-- container -->
<div class="container footer">
	<div class="row">
		<div class="span12"><p>Copyright &copy; 2012 InvoiceBear.com.</p></div>
	</div>
</div>
<% end %>
</body>
</html>

app/views/invoices/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="span12">		
		<div class="row">
			
	    <div class="span8 well">
		<div class="outstanding_invoices span6">
			<h2>Outstanding Invoices:</h2>
			<table class="table-striped table">
			<thead>
			  <tr>
				<th>Date</th>
				<th>Title</th>
			    <th>Number</th>
			    <th>Client</th>
			    <th>Total</th>
			    <th>Status</th>
			    <th>Actions</th>
			  </tr>
			</thead>
			<tbody>
			<% @invoices.outstanding.each do |inv| %>
				<tr>
					<td><%= inv.created_at.to_s(:simple) %></td>
					<td><%= inv.title %></td>
					<td><%= inv.number %></td>
					<td><%= inv.contact.bname %></td>
					<td><%= inv.total %></td>
					<td><%= inv.status %></td>
					<td><%= link_to "View", invoice_path(inv), :class => "btn btn-small" %></td>
				</tr>
			<% end %>
			</tbody>
			</table>
		</div><!-- recent activity -->
		</div>
		
	    <div class="span3 well">
		<div class="outstanding_invoices span5">
			<h2>You are owed:</h2>
			<p class="label label-warning" style="width:120px;font-size:24px;padding:15px;"><%= number_to_currency(@owed) %></p>
			<h2>You billed:</h2>
			<p class="label label-info" style="width:120px;font-size:24px;padding:15px;"><%= number_to_currency(@billed) %></p>
			<h2>You collected:</h2>
			<p class="label label-success" style="width:120px;font-size:24px;padding:15px;"><%= number_to_currency(@received) %></p>
		</div><!-- recent activity -->
		</div>
		
		</div><!-- row -->

	</div>
  </div>
</div>

app/views/invoices/edit.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
<h1>Edit Invoice</h1>
<hr>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>
</div>
</div>
</div>

app/views/invoices/index.html.erb
<h1>Invoices</h1>
		
		<% if notice %>
		<p id="notice" class="alert alert-success"><%= notice %></p>
		<% end %>

		<% if @invoices.count == 0 %>
			<p>Uh oh! You don't have any invoices. Why don't you <%= link_to 'Create An Invoice', new_invoice_path %></p>
		<% else %>
		<table class="table-striped table" id="invoices">
		<thead>
		  <tr>
			<th>Date</th>
		    <th>Number</th>
		    <th>Client</th>
		    <th>Total</th>
		    <th>Status</th>
		    <th>Title</th>
		    <th>Actions</th>
		  </tr>
		</thead>
		<tbody>
		<% @invoices.each do |invoice| %>
		  <tr class="<%= cycle('odd','even') %>">
			<td><%= invoice.created_at.to_s(:simple) %></td>
		    <td><%= invoice.number %></td>
		    <td><%= invoice.contact.fname + " " + invoice.contact.lname %></td>
		    <td><%= number_to_currency(invoice.total) %></td>
                    <% if invoice.status == "draft" %>
		    <td><span class="badge"><%= invoice.status %></span></td>
		    <% elsif invoice.status == "paid" %>
		    <td><span class="badge badge-success"><%= invoice.status %></td>
                    <% else %>
                    <td><span class="badge badge-info"><%= invoice.status %></td>
                    <% end %>
		    <td><%= invoice.title %></td>
		    <td><%= link_to 'View', invoice, :class => "btn" %> <%= link_to 'Edit', edit_invoice_path(invoice), :class => "btn" %> <%= link_to 'Delete', invoice, confirm: 'Are you sure?', method: :delete, :class => "btn btn-danger" %> <%= link_to "View Pdf", invoice_path(invoice, :format => :pdf), :class=> "btn", :target => '_blank' %> </td>
		  </tr>
		<% end %>
		</tbody>
		</table>
      </div>

	  <div class="span3">
	  	<%= link_to 'New Invoice', new_invoice_path, :class => "btn btn-primary" %>
	  </div>
		<% end %>

app/views/invoices/new.html.erb
<div class="row">
	<div class="span12">
		<h1>Create New Invoice</h1>
		<% if current_user.contacts.count == 0 %>
		<p id="notice" class="alert alert-warn">You don't have any contacts yet to create an invoice for. Please <%= link_to "Create a Contact", new_contact_path %> first.</p>
		<% else %>
		<hr>
		<%= render 'form' %>
</div>
</div>
<% end %>

app/views/invoices/show.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
<p id="notice"><%= notice %></p>
<h1>Invoice (<%= number_to_currency(@invoice.total) %>)</h1>

<div id="invoice_options" align="right">
<a href="/invoices/send_invoice_notification/<%= @invoice.id %>" class="btn btn-info">Send to Client</a>
<%= link_to "Edit Invoice", edit_invoice_path(@invoice), :class => "btn" %>
</div>

<span class="ribbon"><%= @invoice.status %>
	</span>

<div class="field">
	<b>Invoice Summary:</b>
	<%= @invoice.title %>
</div>
<div class="field">
	<b>Invoice Date:</b>
	<%= @invoice.created_at.to_s(:simple) %>
</div>

<p>
	<table class="table table-condensed">
	<tr class="header">
	<td>Description</td>
	<td>Unit Cost</td>
	<td>Quantity</td>
	<td>Discount</td>
	<td>Total</td>
	</tr>

	<% @invoice.items.each do |item| %>
	<tr>
	<td class="invoice_description"><%= item.description %></td>
	<td class="invoice_unit_cost"><%= item.unit_cost %></td>
	<td class="invoice_quantity"><%= item.quantity %></td>
	<td class="invoice_discount"><%= number_to_percentage(item.discount) %></td>
	<td class="invoice_item_total"><%= item.total_price %></td>
	</tr>
	<% end %>
	</table>
</p>

</div>
</div>
</div>