config/routes.rb
Invoicebear::Application.routes.draw do
  get "dashboard/show"

  resources :payment_notifications

  get "public_pages/index"

  resources :users
  resource :session, :controller => 'user_sessions'

  resources :items

  resources :contacts

  resources :invoices

     match 'features' => 'public_pages#features', :as => :features
     match 'pricing' => 'public_pages#pricing', :as => :pricing
     match 'about' => 'public_pages#about', :as => :about
     match 'contact-us' => 'public_pages#contact', :as => :contact_us
     
     match 'login' => 'user_sessions#new', :as => :login
     match 'logout' => 'user_sessions#destroy', :as => :logout
     match 'signup' => 'users#new', :as => :sign_up
     
     match 'dashboard' => 'invoices#dashboard', :as => :dashboard
     
     match 'inv/:invoice_id' => 'invoices#client_show', :as => :client_show
     
     match 'invoices/send_invoice_notification/:invoice_id' => 'invoices#send_invoice_notification'

   root :to => 'public_pages#index'

end

app/controllers/public_pages_controller.rb
class PublicPagesController < ApplicationController

  layout nil

  def index
  end
  
  def features
  end
  
  def pricing
  end
  
  def about
  end
  
  def contact
  end

end

app/helpers/public_pages_helper.rb
module PublicPagesHelper
end

app/views/public_pages/about.html.erb
<html>
<head>
  <title>InvoiceBear | About Us</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body> 
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">InvoiceBear</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><a href="/">Home</a></li>
              <li class="active"><a href="/about">About</a></li>
              <li><a href="/features">Features</a></li>
              <li><a href="/pricing">Pricing</a></li>
              <li><a href="/contact">Contact</a></li>
            </ul>
            <ul class="nav pull-right">
				<% if current_user %>
				  <li class="dropdown">
				    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged in as <%= current_user.email %> <b class="caret"></b></a>
					  <ul class="dropdown-menu">
					    <li><a href="/invoices">Dashboard</a></li>
					    <li><%= link_to "My Account", edit_user_path(current_user) %></li>
					    <li class="divider"></li>
					    <li class="separated"><%= link_to "Logout", session_path, :method => :delete %></li>
					  </ul>
				  </li>
				<% else %>
			  <li><%= link_to 'Sign Up!', new_user_path %></li>
			  <li class="divider-vertical"></li>
              <li><%= link_to 'Login', new_session_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container main-content">
      <!-- Example row of columns -->
      <div class="row">
        <div class="span12">
			<div class="row">
				<div class="span3">
          			<h2>Independent Contractors</h2>
           			<p>Invoice Bear makes billing your clients simple and fast by providing the most user-friendly experience on the market. We’ve focused on providing just what you need in an intuitive design to make the invoicing process seamless for our customers.  		</p>
          			<p><a class="btn" href="#">View details &raquo;</a></p>
				</div>
				<div class="span9">
          			<h2>Independent Contractors</h2>
           			<p>Invoice Bear makes billing your clients simple and fast by providing the most user-friendly experience on the market. We’ve focused on providing just what you need in an intuitive design to make the invoicing process seamless for our customers.  		</p>
          			<p><a class="btn" href="#">View details &raquo;</a></p>
				</div>
			</div>
        </div>
      </div>

      <hr>

     <footer>
        <p>&copy; 2012 InvoiceBear</p>
      </footer>

    </div> <!-- /container -->
</body>
</html>

app/views/public_pages/contact.html.erb
<html>
<head>
  <title>InvoiceBear | Contact Us</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body> 
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">InvoiceBear</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><a href="/">Home</a></li>
              <li><a href="/about">About</a></li>
              <li><a href="/features">Features</a></li>
              <li><a href="/pricing">Pricing</a></li>
              <li class="active"><a href="/contact">Contact</a></li>
            </ul>
            <ul class="nav pull-right">
				<% if current_user %>
				  <li class="dropdown">
				    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged in as <%= current_user.email %> <b class="caret"></b></a>
					  <ul class="dropdown-menu">
					    <li><a href="/invoices">Dashboard</a></li>
					    <li><%= link_to "My Account", edit_user_path(current_user) %></li>
					    <li class="divider"></li>
					    <li class="separated"><%= link_to "Logout", session_path, :method => :delete %></li>
					  </ul>
				  </li>
				<% else %>
			  <li><%= link_to 'Sign Up!', new_user_path %></li>
			  <li class="divider-vertical"></li>
              <li><%= link_to 'Login', new_session_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container main-content">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>Contact Us</h1>
        <p>Have any questions? Need support? Feel free to contact us at <a href="mailto:support@invoicebear.com">support@invoicebear.com</a> and we will be sure to answer back as quickly as possible!</p>
      </div>

      <hr>

      <footer>
        <p>&copy; 2012 InvoiceBear</p>
      </footer>

    </div> <!-- /container -->
</body>
</html>

app/views/public_pages/features.html.erb
<html>
<head>
  <title>InvoiceBear | Features</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body> 
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">InvoiceBear</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><a href="/">Home</a></li>
              <li><a href="/about">About</a></li>
              <li class="active"><a href="/features">Features</a></li>
              <li><a href="/pricing">Pricing</a></li>
              <li><a href="/contact">Contact</a></li>
            </ul>
            <ul class="nav pull-right">
				<% if current_user %>
				  <li class="dropdown">
				    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged in as <%= current_user.email %> <b class="caret"></b></a>
					  <ul class="dropdown-menu">
					    <li><a href="/invoices">Dashboard</a></li>
					    <li><%= link_to "My Account", edit_user_path(current_user) %></li>
					    <li class="divider"></li>
					    <li class="separated"><%= link_to "Logout", session_path, :method => :delete %></li>
					  </ul>
				  </li>
				<% else %>
			  <li><%= link_to 'Sign Up!', new_user_path %></li>
			  <li class="divider-vertical"></li>
              <li><%= link_to 'Login', new_session_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container main-content">
      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>Invoice Management</h2>
           <p>Invoice Bear makes billing your clients simple and fast by providing the most user-friendly experience on the market. We’ve focused on providing just what you need in an intuitive design to make the invoicing process seamless for our customers.  </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
        <div class="span4">
          <h2>Client Management</h2>
           <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
       </div>
        <div class="span4">
          <h2>Insights and Analytics</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>Invoice Management</h2>
           <p>Invoice Bear makes billing your clients simple and fast by providing the most user-friendly experience on the market. We’ve focused on providing just what you need in an intuitive design to make the invoicing process seamless for our customers.  </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
        <div class="span4">
          <h2>Client Management</h2>
           <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
       </div>
        <div class="span4">
          <h2>Insights and Analytics</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

     <footer>
        <p>&copy; 2012 InvoiceBear</p>
      </footer>

    </div> <!-- /container -->

</body>
</html>

app/views/public_pages/index.html.erb
<html>
<head>
  <title>InvoiceBear | Simple Fast Invoice Creation!</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body> 
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">InvoiceBear</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="/">Home</a></li>
              <li><a href="/about">About</a></li>
              <li><a href="/features">Features</a></li>
              <li><a href="/pricing">Pricing</a></li>
              <li><a href="/contact">Contact</a></li>
            </ul>
            <ul class="nav pull-right">
				<% if current_user %>
				  <li class="dropdown">
				    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged in as <%= current_user.email %> <b class="caret"></b></a>
					  <ul class="dropdown-menu">
					    <li><a href="/invoices">Dashboard</a></li>
					    <li><%= link_to "My Account", edit_user_path(current_user) %></li>
					    <li class="divider"></li>
					    <li class="separated"><%= link_to "Logout", logout_path, :method => :delete %></li>
					  </ul>
				  </li>
				<% else %>
			  <li><%= link_to 'Sign Up!', sign_up_path %></li>
			  <li class="divider-vertical"></li>
              <li><%= link_to 'Login', login_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container main-content">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit" style="background-image:url(/assets/invoicebear_screenshot.jpg);background-repeat:no-repeat;background-position:95% 100%;">
        <h1>Invoice Bear</h1>
       <p>Simple Fast Invoice Creation and <br />Billing System for Independent Contractors <br />on the Go! </p>
        <p><a class="btn btn-primary btn-large" href="/users/new">Sign Up &raquo;</a></p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>Simple</h2>
           <p>Invoice Bear makes billing your clients simple and fast by providing an intuitvie design and the most user-friendly experience on the market.  </p>
          <p><a class="btn" href="/features">View Features &raquo;</a></p>
        </div>
        <div class="span4">
          <h2>Affordable</h2>
           <p>Since we deliver a product that focusing on the needs of independent contractors we also have worked to ensure our product meets their budgets. Try it out for free today! </p>
          <p><a class="btn" href="/pricing">View Pricing &raquo;</a></p>
       </div>
        <div class="span4">
          <h2>Mobile</h2>
          <p> Invoice Bear works across all smartphones and tablets, giving our customers the ability to create and edit their clients and invoices on the go! </p>
          <p><a class="btn" href="/features">Learn More &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; 2012 InvoiceBear</p>
      </footer>

    </div> <!-- /container -->
</body>
</html>

app/views/public_pages/pricing.html.erb
<html>
<head>
  <title>InvoiceBear | Pricing</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body> 
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">InvoiceBear</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><a href="/">Home</a></li>
              <li><a href="/about">About</a></li>
              <li><a href="/features">Features</a></li>
              <li class="active"><a href="/pricing">Pricing</a></li>
              <li><a href="/contact">Contact</a></li>
            </ul>
            <ul class="nav pull-right">
				<% if current_user %>
				  <li class="dropdown">
				    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged in as <%= current_user.email %> <b class="caret"></b></a>
					  <ul class="dropdown-menu">
					    <li><a href="/invoices">Dashboard</a></li>
					    <li><%= link_to "My Account", edit_user_path(current_user) %></li>
					    <li class="divider"></li>
					    <li class="separated"><%= link_to "Logout", session_path, :method => :delete %></li>
					  </ul>
				  </li>
				<% else %>
			  <li><%= link_to 'Sign Up!', new_user_path %></li>
			  <li class="divider-vertical"></li>
              <li><%= link_to 'Login', new_session_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container main-content">
      <!-- Example row of columns -->
      <div class="row">
        <div class="span12">
          <h2>Pricing</h2>
           <p>Invoice Bear makes billing your clients simple and fast by providing the most user-friendly experience on the market. We’ve focused on providing just what you need in an intuitive design to make the invoicing process seamless for our customers.  </p>
          <table class="table table-striped" style="width:80%;margin:0 auto;">
		 	<tr>
				<td>Basic</td>
				<td>Premium</td>
			</tr>
			<tr>
				<td>Basic</td>
				<td>Premium</td>
			</tr>

		</table>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; 2012 InvoiceBear</p>
      </footer>

    </div> <!-- /container -->
</body>
</html>