config/routes.rb
Invoicebear::Application.routes.draw do
  get "dashboard/show"

  resources :payment_notifications

  get "public_pages/index"

  resources :users
  resource :session, :controller => 'user_sessions'

  resources :items

  resources :contacts

  resources :invoices

     match 'features' => 'public_pages#features', :as => :features
     match 'pricing' => 'public_pages#pricing', :as => :pricing
     match 'about' => 'public_pages#about', :as => :about
     match 'contact-us' => 'public_pages#contact', :as => :contact_us
     
     match 'login' => 'user_sessions#new', :as => :login
     match 'logout' => 'user_sessions#destroy', :as => :logout
     match 'signup' => 'users#new', :as => :sign_up
     
     match 'dashboard' => 'invoices#dashboard', :as => :dashboard
     
     match 'inv/:invoice_id' => 'invoices#client_show', :as => :client_show
     
     match 'invoices/send_invoice_notification/:invoice_id' => 'invoices#send_invoice_notification'

   root :to => 'public_pages#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InvoiceBear</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <link href='http://fonts.googleapis.com/css?family=Maven+Pro' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">InvoiceBear</a>
        <div class="nav-collapse">
          <ul class="nav">
			<% if current_user %>
            <li><%= link_to "Dashboard", dashboard_path %></li>
            <li><%= link_to "Invoices", invoices_path %></li>
            <li><%= link_to "Contacts", contacts_path %></li>
			<% else %>
			<li class="active"><a href="/">Home</a></li>
            <li><a href="/about">About</a></li>
            <li><a href="/features">Features</a></li>
            <li><a href="/pricing">Pricing</a></li>
            <li><a href="/contact">Contact</a></li>
			<% end %>
          </ul>
		  <ul class="nav pull-right">
			<% if current_user %>
			<li><a href="#">Welcome, <%= current_user.username %>!</a></li>
			<li class="divider-vertical"></li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
					<li class="divider"></li>
					<li><%= link_to "Logout", logout_path, :method => :delete %></li>
				</ul>
			</li>
			<% else %>
			<li><%= link_to "Register", sign_up_path %></li>
			<li><%= link_to "Login", login_path %></li>
				<% end %>
		  </ul>
        </div>
      </div>
    </div>
  </div><!-- navbar -->
<div class="container main-content">
  <div class="row">
    <div class="span12">
        <%= yield %>
	</div>
  </div>
</div>
<div class="container footer" style="color:white;">
	<div class="row">
		<div class="span12"><p>Copyright &copy; 2012 InvoiceBear.com</p></div>
	</div>
</div>
</body>
</html>